import Head from 'next/head'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ 
  weight: ['400', '600', '700'],
  subsets: ['latin']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatif - Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={poppins.className}>
        <h1>Whatif</h1>
      </main>
    </>
  )
}
