import Head from 'next/head'
import { getCssText } from '@/styles'
import Header from '@/components/header'

import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatif - Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style id='stitches' dangerouslySetInnerHTML={{__html: getCssText()}}></style>
      </Head>
      <main className={poppins.className}>
        <Header />
      </main>
      </>
  )
}
